Repository Substra/substra-documentation, pull requests merged in 2020-09, with the labels that each got.

#110 Remove pkhash from doc
  docs/_sources/debugging.md.txt
  docs/debugging.html
  docs/searchindex.js
  src/debugging.md
Labels: documentation, enhancement

#115 Add helm3
  .travis.yml
  docs/_sources/publish.md.txt
  docs/_sources/setup/local_install_skaffold.md.txt
  docs/_static/pygments.css
  docs/searchindex.js
  docs/setup/local_install_skaffold.html
  src/publish.md
  src/setup/local_install_skaffold.md
Labels: documentation

#117 Add Substra-examples
  docs/_sources/usage.md.txt
  docs/searchindex.js
  docs/usage.html
  src/usage.md
Labels: Use cases, documentation

#119 Add usage section to troubleshooting
  docs/_sources/setup/further_resources.md.txt
  docs/searchindex.js
  docs/setup/further_resources.html
  docs/setup/index.html
  src/setup/further_resources.md
Labels: documentation, enhancement
