Repository Substra/substra-documentation, pull requests merged in 2021-01, with the labels that each got.

#129 Update Sphinx version
  docs/setup/local_install_skaffold.html
  requirements.txt
Labels: documentation

#144 Update demo login commands
  conf.py
  docs/CONTRIBUTING.html
  docs/_sources/setup/demo.md.txt
  docs/_static/basic.css
  docs/_static/doctools.js
  docs/_static/documentation_options.js
  docs/_static/jquery-3.5.1.js
  docs/_static/jquery.js
  docs/_static/language_data.js
  docs/_static/searchtools.js
  docs/architecture.html
  docs/concepts.html
  docs/debugging.html
  docs/faq.html
  docs/genindex.html
  docs/glossary.html
  docs/index.html
  docs/objects.inv
  docs/overview.html
  docs/publish.html
  docs/search.html
  docs/searchindex.js
  docs/setup/demo.html
  docs/setup/further_resources.html
  docs/setup/index.html
  docs/setup/local_install_skaffold.html
  docs/usage.html
  src/setup/demo.md
Labels: documentation

#118 Cheatsheets (CLI and VM) & TOC update
  README.md
  docs/CONTRIBUTING.html
  docs/_sources/cheatsheet_cli.md.txt
  docs/_sources/debugging.md.txt
  docs/_sources/demo.md.txt
  docs/_sources/index.rst.txt
  docs/_sources/setup/cheatsheet_vm.md.txt
  docs/_sources/setup/index.rst.txt
  docs/_sources/usage.md.txt
  docs/architecture.html
  docs/cheatsheet_cli.html
  docs/concepts.html
  docs/debugging.html
  docs/demo.html
  docs/faq.html
  docs/genindex.html
  docs/glossary.html
  docs/index.html
  docs/objects.inv
  docs/overview.html
  docs/publish.html
  docs/search.html
  docs/searchindex.js
  docs/setup/cheatsheet_vm.html
  docs/setup/further_resources.html
  docs/setup/index.html
  docs/setup/local_install_skaffold.html
  docs/usage.html
  src/cheatsheet_cli.md
  src/debugging.md
  src/demo.md
  src/index.rst
  src/setup/cheatsheet_vm.md
  src/setup/index.rst
  src/usage.md
Labels: documentation, enhancement

#149 Update copyright year
  .github/workflows/build.yml
  conf.py
  docs/CONTRIBUTING.html
  docs/architecture.html
  docs/cheatsheet_cli.html
  docs/concepts.html
  docs/debugging.html
  docs/demo.html
  docs/faq.html
  docs/genindex.html
  docs/glossary.html
  docs/index.html
  docs/overview.html
  docs/publish.html
  docs/search.html
  docs/setup/cheatsheet_vm.html
  docs/setup/further_resources.html
  docs/setup/index.html
  docs/setup/local_install_skaffold.html
  docs/usage.html
Labels: documentation

#151 Skaffold deploy
  docs/_sources/setup/local_install_skaffold.md.txt
  docs/searchindex.js
  docs/setup/local_install_skaffold.html
  src/setup/local_install_skaffold.md
Labels: Deployment, documentation

#122 Helm install values
  docs/_sources/setup/local_install_skaffold.md.txt
  docs/searchindex.js
  docs/setup/local_install_skaffold.html
  src/setup/local_install_skaffold.md
Labels: Deployment, documentation, enhancement
